# Global configuration
global:
  # Namespace to deploy the resources
  namespace: default

# NVIDIA FS DaemonSet configuration
nvidiaFs:
  # Enable/disable the NVIDIA FS DaemonSet
  enabled: true
  
  # Image configuration
  image:
    repository: ubuntu
    tag: "22.04"
    pullPolicy: IfNotPresent
  
  # Kernel version to use for NVIDIA GDS installation
  kernelVersion: "6.5.13-65-650-4141-22041-coreweave-amd64-85c45edc"
  
  # NVIDIA GDS version
  nvidiaGdsVersion: "12.9.1-1"
  
  # Resource configuration
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
  
  # Node selector for targeting specific nodes
  nodeSelector: {}
  
  # Tolerations for scheduling on tainted nodes
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: NoSchedule
      operator: Exists
  
  # Additional environment variables
  env: []

# Weka AMG DaemonSet configuration
wekaAmg:
  # Enable/disable the Weka AMG DaemonSet
  enabled: true
  
  # Image configuration
  image:
    repository: sdimitro509/amg
    tag: "latest"
    pullPolicy: IfNotPresent
  
  # Resource configuration
  resources:
    requests:
      rdmaIb: 1
      nvidiaGpu: 8
      cpu: "16"
      memory: "128Gi"
    limits:
      rdmaIb: 1
      nvidiaGpu: 8
      cpu: "16"
      memory: "128Gi"
  
  # NCCL and UCX environment configuration
  env:
    ncclSocketIfname: "=enp157s0np0,enp158s0np0"
    ncclIbHca: "ibp"
    ucxNetDevices: "ibp0:1,ibp1:1,ibp2:1,ibp3:1,ibp4:1,ibp5:1,ibp6:1,ibp7:1"
    ncclDebug: "INFO"
    nvidiaGdrcopy: "enabled"
    hfToken: ""
    hfPath: "/mnt/weka/hf_cache"
  
  # Additional environment variables
  additionalEnv: []
  
  # Persistent Volume Claim name for Weka filesystem
  pvc:
    name: "wekafs-amg"
    mountPath: "/mnt/weka"
  
  # Update strategy configuration
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  
  # Node selector for targeting specific nodes
  nodeSelector: {}
  
  # Tolerations for scheduling on tainted nodes
  tolerations: []

# Additional labels to apply to all resources
additionalLabels: {}

# Additional annotations to apply to all resources
additionalAnnotations: {}
