image:
  repository: sdimitro509/amg
  tag: "latest"
  pullPolicy: IfNotPresent
resources:
  # We default to 8 assuming DGX. Configure accordingly.
  gpu: 8
  # RDMA resource configuration.
  rdma:
    # The 'name' must match the full resource name advertised by the Network Operator's
    # device plugin, which was configured in the NicClusterPolicy. We default to 1 dev
    # per GPU.
    name: "rdma/rdma_shared"
    count: 8
  # Standard CPU and memory requests/limits can be added here if needed.
  # cpu: "32"
  # memory: "256Gi"

# Dependency configuration
network-operator:
  enabled: true
  # Override any values from the network-operator chart
  sriov-network-operator:
    images:
      # TODO: Not sure if this is strictly needed - adding as nice to have for now
      rdmaCni: ghcr.io/k8snetworkplumbingwg/rdma-cni:v1.3.0
  nfd:
    enabled: true # This is the default but we explicitly set it here and disable it for gpu-operator

gpu-operator:
  enabled: true
  # Override any values from the gpu-operator chart
  rdma:
    enabled: true # Enabled to use legacy `nvidia-peermem`. TODO: Disable once we update kernel version & test
    useHostMofed: false # Disable to avoid using dma_buf and network dev drivers from the host
  gds:
    enabled: true # Enables GDS for clusters that use NVIDIA's Network Operator (like ours)
  gdrcopy:
    enabled: true # TODO: Not sure if this is strictly needed. Adding as nice to have for now
  nfd:
    enabled: false # Set it to false to avoid conflict from the network-operator

# NIC Cluster Policy configuration
nicClusterPolicy:
  # -- Enable deployment of NicClusterPolicy
  enabled: false
  # -- Name of the NicClusterPolicy resource
  name: "nic-cluster-policy"
  
  # OFED Driver configuration
  ofedDriver:
    # -- OFED driver container repository
    repository: "nvcr.io/nvidia/mellanox"
    # -- OFED driver container image name
    image: "doca-driver"
    # -- OFED driver version
    version: "25.04-0.6.1.0-2"
    # -- Force use of precompiled drivers
    forcePrecompiled: false
    # -- Image pull secrets for OFED driver
    imagePullSecrets: []
    # -- Termination grace period in seconds
    terminationGracePeriodSeconds: 300
    
    # Probe configurations
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    
    # Upgrade policy configuration
    upgradePolicy:
      autoUpgrade: true
      maxParallelUpgrades: 1
      safeLoad: false
      drain:
        enable: true
        force: true
        podSelector: ""
        timeoutSeconds: 300
        deleteEmptyDir: true

  # RDMA Shared Device Plugin configuration
  rdmaSharedDevicePlugin:
    # -- RDMA plugin container repository
    repository: "ghcr.io/mellanox"
    # -- RDMA plugin container image name
    image: "k8s-rdma-shared-dev-plugin"
    # -- RDMA plugin version
    version: "v1.5.3"
    # -- Image pull secrets for RDMA plugin
    imagePullSecrets: []
    # -- Resource name for RDMA devices
    resourceName: "rdma_shared"
    # -- Maximum number of RDMA HCA devices
    rdmaHcaMax: 1000
    
    # Device selectors
    selectors:
      # -- List of vendor IDs to match (empty means all)
      vendors: []
      # -- List of device IDs to match (empty means all)
      deviceIDs: []
      # -- List of drivers to match (empty means all)
      drivers: []
      # -- List of interface names to match
      # For H100A hardware, use: ["ibp24s0", "ibp206s0", "ibp220s0", "ibp64s0", "ibp79s0", "ibp94s0", "ibp154s0", "ibp192s0"]
      # For other hardware, update accordingly
      ifNames: []
      # -- List of link types to match (empty means all)
      linkTypes: []
