{{- if .Values.wekaAmg.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "amg-cw-chart.wekaamg.name" . }}
  labels:
    {{- include "amg-cw-chart.wekaamg.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "amg-cw-chart.wekaamg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amg-cw-chart.wekaamg.selectorLabels" . | nindent 8 }}
      {{- with .Values.additionalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: true
      hostIPC: true
      containers:
        - name: amg-container
          image: {{ .Values.wekaAmg.image.repository }}:{{ .Values.wekaAmg.image.tag }}
          imagePullPolicy: {{ .Values.wekaAmg.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
            privileged: true
          resources:
            requests:
              rdma/ib: {{ .Values.wekaAmg.resources.requests.rdmaIb }}
              nvidia.com/gpu: {{ .Values.wekaAmg.resources.requests.nvidiaGpu }}
              cpu: {{ .Values.wekaAmg.resources.requests.cpu | quote }}
              memory: {{ .Values.wekaAmg.resources.requests.memory | quote }}
            limits:
              rdma/ib: {{ .Values.wekaAmg.resources.limits.rdmaIb }}
              nvidia.com/gpu: {{ .Values.wekaAmg.resources.limits.nvidiaGpu }}
              cpu: {{ .Values.wekaAmg.resources.limits.cpu | quote }}
              memory: {{ .Values.wekaAmg.resources.limits.memory | quote }}
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 60; done;"]
          env:
            - name: NCCL_SOCKET_IFNAME
              value: {{ .Values.wekaAmg.env.ncclSocketIfname | quote }}
            - name: NCCL_IB_HCA
              value: {{ .Values.wekaAmg.env.ncclIbHca | quote }}
            - name: UCX_NET_DEVICES
              value: {{ .Values.wekaAmg.env.ucxNetDevices | quote }}
            - name: NCCL_DEBUG
              value: {{ .Values.wekaAmg.env.ncclDebug | quote }}
            - name: NVIDIA_GDRCOPY
              value: {{ .Values.wekaAmg.env.nvidiaGdrcopy | quote }}
            - name: HF_TOKEN
              value: {{ .Values.wekaAmg.env.hfToken | quote }}
            - name: HF_PATH
              value: {{ .Values.wekaAmg.env.hfPath | quote }}
            {{- with .Values.wekaAmg.additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: weka-pvc
              mountPath: {{ .Values.wekaAmg.pvc.mountPath }}
      volumes:
        - name: weka-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.wekaAmg.pvc.name }}
      {{- with .Values.wekaAmg.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wekaAmg.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: {{ .Values.wekaAmg.updateStrategy.type }}
    {{- if eq .Values.wekaAmg.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.wekaAmg.updateStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.wekaAmg.updateStrategy.rollingUpdate.maxUnavailable }}
    {{- end }}
{{- end }}
