apiVersion: v1
kind: Pod
metadata:
  name: {{ include "amg-chart.fullname" . }}
  labels:
    {{- include "amg-chart.labels" . | nindent 4 }}
spec:
  restartPolicy: OnFailure
  # TODO: remove next
  hostNetwork: true
  # TODO: remove next
  hostIPC: true
  containers:
    - name: amg-container
      image: "{{.Values.image.repository }}:{{.Values.image.tag }}"
      securityContext:
        # TODO: check if actually needed
        capabilities:
          add: [ "IPC_LOCK" ]
      imagePullPolicy: {{.Values.image.pullPolicy }}
      resources:
        requests:
          nvidia.com/gpu: {{.Values.resources.gpu | quote }}
          {{.Values.resources.rdma.name }}: {{.Values.resources.rdma.count | quote }}
        limits:
          nvidia.com/gpu: {{.Values.resources.gpu | quote }}
          {{.Values.resources.rdma.name }}: {{.Values.resources.rdma.count | quote }}
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 60; done;"]
      env:
        - name: HF_TOKEN
          value: {{ .Values.env.hfToken | quote }}
        - name: HF_PATH
          value: {{ .Values.env.hfPath | quote }}
      volumeMounts:
        - name: weka-storage
          mountPath: /mnt/weka
  volumes:
    - name: weka-storage # TODO: Change to PVC
      hostPath:
        path: {{ .Values.volume.hostPath | quote }}
